module Deployments
  class OctokitGithubService

    def create_release(oauth_token, name, release_name, sha)
      binding.pry
      client(oauth_token).create_release(name, release_name, {
        target_commitish: sha,
        name:             release_name,
        body:             "Release generated by http://deploymy.codes based on the commit #{sha}.",
        draft:            false,
        prerelease:       false
      })
    end

    private

    def client(oauth_token)
      Octokit::Client.new(access_token: oauth_token, auto_paginate: true)
    end
  end
end
