development:
  host: localhost
  port: 5432
  username: deploy_my_codes
  password:
  database: deploy_my_codes_development

test:
  host: localhost
  port: 5432
  username: deploy_my_codes
  password:
  database: deploy_my_codes_test

production:
  host:
  port:
  username:
  password:
  database:
